yelp_clone/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "restaurants#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews do
      collection do
        delete  "destroy"  => "reviews#delete",  :as => 'delete_review'
      end
    end
  end
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session2
  end
end

yelp_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

yelp_clone/app/models/restaurant.rb
class Restaurant < ApplicationRecord

  has_many :reviews,
          -> { extending WithUserAssociationExtension },
          dependent: :destroy

  belongs_to :user


  validates :name, length: { minimum: 3 }, uniqueness: true

end

yelp_clone/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
  belongs_to :restaurant
  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }
end

yelp_clone/app/models/user.rb
class User < ApplicationRecord

  has_many :reviews, dependent: :destroy
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :restaurants

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
    #  user.name = auth.info.name   # assuming the user model has a name
    #  user.image = auth.info.image # assuming the user model has an image
     # If you are using confirmable and the provider(s) you use validate emails,
     # uncomment the line below to skip the confirmation emails.
     # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end

end

yelp_clone/app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
    attributes[:user] ||= user
    create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end

end

yelp_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def new_session_path(scope)
    new_user_session_path
  end
end

yelp_clone/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    # require 'pry'; binding.pry
    if Restaurant.find(params[:id]).user == current_user
      @restaurant = Restaurant.find(params[:id])
    else
      flash[:notice] = "Cannot Edit a Restaurant you don't own"
      redirect_to restaurants_path
    end

  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to '/restaurants'
  end

  def destroy
    if Restaurant.find(params[:id]).user == current_user
      @restaurant = Restaurant.find(params[:id])
      name = @restaurant.name
      @restaurant.destroy
      flash[:notice] = "#{name} deleted successfully"
      redirect_to '/restaurants'
    else
      flash[:notice] = "Cannot Delete a Restaurant you don't own"
      redirect_to '/restaurants'
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description)
  end

end

yelp_clone/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :authenticate_user!
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build_with_user(review_params, current_user)

    if @review.save
      redirect_to '/restaurants'
    else
      if @review.errors[:user]
        redirect_to restaurants_path, alert: "You have already reviewed this restaurant"
      else
        render :new
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review deleted successfully"
    redirect_to '/restaurants'
  end

  private

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end
end

yelp_clone/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

yelp_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

yelp_clone/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

yelp_clone/app/helpers/reviews_helper.rb
module ReviewsHelper
end

yelp_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YelpClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
      <%= link_to "Sign up", new_user_registration_path %>
    <% end %>
  </head>

  <body>
    <%= alert %>
    <%= notice %>
    <%= yield %>
  </body>
</html>

yelp_clone/app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

yelp_clone/app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
    <h2> <%= link_to restaurant.name, restaurant_path(restaurant) %> </h2>
    <%# <% if user_signed_in? %1> %>
      <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>
      <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
      <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>
      <%# <% end %1> %>
    <% restaurant.reviews.each do |review| %>
      <li><%= review.thoughts %>  <%=review.rating %> -  <%= review.user.email %>
        <% if current_user == review.user %>
          <%= link_to "Delete review", restaurant_review_path(review.restaurant_id, review.id), method: :delete %>
        <% end %>
      </li>
    <% end %>
  <% end %>
<% else %>
  No restaurants yet
<% end %>

<a href='/restaurants/new'>Add a restaurant</a>

yelp_clone/app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

yelp_clone/app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
<p><%= @restaurant.description %></p>

yelp_clone/app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.submit 'Leave Review' %>
<% end %>